#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jan 28 16:12:06 2019

@author: 3700052
"""
from soccersimulator import Ball, settings, Strategy, SoccerAction, Vector2D, SoccerTeam, Simulation, show_simu
from soccersimulator.settings  import GAME_WIDTH, GAME_HEIGHT


class SuperState (object):
    def __init__ (self, state, id_team, id_player):
        self.state = state
        self.id_team = id_team
        self.id_player = id_player
        
    @property
    def ball(self):
        return self.state.ball.position
    
    @property
    def player(self):
        return self.state.player_state (self.id_team, self.id_player).position
    
    @property
    def goal(self):
        if(self.id_team == 2):
            return Vector2D(0,GAME_HEIGHT/2)
        else :
            return Vector2D(GAME_WIDTH, GAME_HEIGHT/2)
        
    @property
    def angle(self):
        return math.atan2(self.y, self.x)
    
    
    
    @property
    def liste(self):
        for i in range (0,GAME_WIDTH):
            for j in range (0,GAME_HEIGHT):
                if (state.player_state(id_team ,id_player).position.x = i) && (state.player_state(id_team ,id_player).position.y = j):
    
    @property
    def near(self):
        
        
        
class SimpleStrategy (Strategy):
    def __init__ (self, action, name):
        super().__init__(name)
        self.action = action

    def compute_strategy (self, state ,id_team ,id_player):
        s = SuperState (state, id_team, id_player)
        return self.action(s)
